#pragma once

#include <map>

#include <api.hxx>

template<>
struct std::formatter<XrResult> : std::formatter<std::string>
{
    template<typename Context>
    auto format(const XrResult &result, Context &context) const
    {
        static const std::map<XrResult, const char *> map
        {
            {
                XR_SUCCESS,
                "XR_SUCCESS"
            },
            {
                XR_TIMEOUT_EXPIRED,
                "XR_TIMEOUT_EXPIRED"
            },
            {
                XR_SESSION_LOSS_PENDING,
                "XR_SESSION_LOSS_PENDING"
            },
            {
                XR_EVENT_UNAVAILABLE,
                "XR_EVENT_UNAVAILABLE"
            },
            {
                XR_SPACE_BOUNDS_UNAVAILABLE,
                "XR_SPACE_BOUNDS_UNAVAILABLE"
            },
            {
                XR_SESSION_NOT_FOCUSED,
                "XR_SESSION_NOT_FOCUSED"
            },
            {
                XR_FRAME_DISCARDED,
                "XR_FRAME_DISCARDED"
            },
            {
                XR_ERROR_VALIDATION_FAILURE,
                "XR_ERROR_VALIDATION_FAILURE"
            },
            {
                XR_ERROR_RUNTIME_FAILURE,
                "XR_ERROR_RUNTIME_FAILURE"
            },
            {
                XR_ERROR_OUT_OF_MEMORY,
                "XR_ERROR_OUT_OF_MEMORY"
            },
            {
                XR_ERROR_API_VERSION_UNSUPPORTED,
                "XR_ERROR_API_VERSION_UNSUPPORTED"
            },
            {
                XR_ERROR_INITIALIZATION_FAILED,
                "XR_ERROR_INITIALIZATION_FAILED"
            },
            {
                XR_ERROR_FUNCTION_UNSUPPORTED,
                "XR_ERROR_FUNCTION_UNSUPPORTED"
            },
            {
                XR_ERROR_FEATURE_UNSUPPORTED,
                "XR_ERROR_FEATURE_UNSUPPORTED"
            },
            {
                XR_ERROR_EXTENSION_NOT_PRESENT,
                "XR_ERROR_EXTENSION_NOT_PRESENT"
            },
            {
                XR_ERROR_LIMIT_REACHED,
                "XR_ERROR_LIMIT_REACHED"
            },
            {
                XR_ERROR_SIZE_INSUFFICIENT,
                "XR_ERROR_SIZE_INSUFFICIENT"
            },
            {
                XR_ERROR_HANDLE_INVALID,
                "XR_ERROR_HANDLE_INVALID"
            },
            {
                XR_ERROR_INSTANCE_LOST,
                "XR_ERROR_INSTANCE_LOST"
            },
            {
                XR_ERROR_SESSION_RUNNING,
                "XR_ERROR_SESSION_RUNNING"
            },
            {
                XR_ERROR_SESSION_NOT_RUNNING,
                "XR_ERROR_SESSION_NOT_RUNNING"
            },
            {
                XR_ERROR_SESSION_LOST,
                "XR_ERROR_SESSION_LOST"
            },
            {
                XR_ERROR_SYSTEM_INVALID,
                "XR_ERROR_SYSTEM_INVALID"
            },
            {
                XR_ERROR_PATH_INVALID,
                "XR_ERROR_PATH_INVALID"
            },
            {
                XR_ERROR_PATH_COUNT_EXCEEDED,
                "XR_ERROR_PATH_COUNT_EXCEEDED"
            },
            {
                XR_ERROR_PATH_FORMAT_INVALID,
                "XR_ERROR_PATH_FORMAT_INVALID"
            },
            {
                XR_ERROR_PATH_UNSUPPORTED,
                "XR_ERROR_PATH_UNSUPPORTED"
            },
            {
                XR_ERROR_LAYER_INVALID,
                "XR_ERROR_LAYER_INVALID"
            },
            {
                XR_ERROR_LAYER_LIMIT_EXCEEDED,
                "XR_ERROR_LAYER_LIMIT_EXCEEDED"
            },
            {
                XR_ERROR_SWAPCHAIN_RECT_INVALID,
                "XR_ERROR_SWAPCHAIN_RECT_INVALID"
            },
            {
                XR_ERROR_SWAPCHAIN_FORMAT_UNSUPPORTED,
                "XR_ERROR_SWAPCHAIN_FORMAT_UNSUPPORTED"
            },
            {
                XR_ERROR_ACTION_TYPE_MISMATCH,
                "XR_ERROR_ACTION_TYPE_MISMATCH"
            },
            {
                XR_ERROR_SESSION_NOT_READY,
                "XR_ERROR_SESSION_NOT_READY"
            },
            {
                XR_ERROR_SESSION_NOT_STOPPING,
                "XR_ERROR_SESSION_NOT_STOPPING"
            },
            {
                XR_ERROR_TIME_INVALID,
                "XR_ERROR_TIME_INVALID"
            },
            {
                XR_ERROR_REFERENCE_SPACE_UNSUPPORTED,
                "XR_ERROR_REFERENCE_SPACE_UNSUPPORTED"
            },
            {
                XR_ERROR_FILE_ACCESS_ERROR,
                "XR_ERROR_FILE_ACCESS_ERROR"
            },
            {
                XR_ERROR_FILE_CONTENTS_INVALID,
                "XR_ERROR_FILE_CONTENTS_INVALID"
            },
            {
                XR_ERROR_FORM_FACTOR_UNSUPPORTED,
                "XR_ERROR_FORM_FACTOR_UNSUPPORTED"
            },
            {
                XR_ERROR_FORM_FACTOR_UNAVAILABLE,
                "XR_ERROR_FORM_FACTOR_UNAVAILABLE"
            },
            {
                XR_ERROR_API_LAYER_NOT_PRESENT,
                "XR_ERROR_API_LAYER_NOT_PRESENT"
            },
            {
                XR_ERROR_CALL_ORDER_INVALID,
                "XR_ERROR_CALL_ORDER_INVALID"
            },
            {
                XR_ERROR_GRAPHICS_DEVICE_INVALID,
                "XR_ERROR_GRAPHICS_DEVICE_INVALID"
            },
            {
                XR_ERROR_POSE_INVALID,
                "XR_ERROR_POSE_INVALID"
            },
            {
                XR_ERROR_INDEX_OUT_OF_RANGE,
                "XR_ERROR_INDEX_OUT_OF_RANGE"
            },
            {
                XR_ERROR_VIEW_CONFIGURATION_TYPE_UNSUPPORTED,
                "XR_ERROR_VIEW_CONFIGURATION_TYPE_UNSUPPORTED"
            },
            {
                XR_ERROR_ENVIRONMENT_BLEND_MODE_UNSUPPORTED,
                "XR_ERROR_ENVIRONMENT_BLEND_MODE_UNSUPPORTED"
            },
            {
                XR_ERROR_NAME_DUPLICATED,
                "XR_ERROR_NAME_DUPLICATED"
            },
            {
                XR_ERROR_NAME_INVALID,
                "XR_ERROR_NAME_INVALID"
            },
            {
                XR_ERROR_ACTIONSET_NOT_ATTACHED,
                "XR_ERROR_ACTIONSET_NOT_ATTACHED"
            },
            {
                XR_ERROR_ACTIONSETS_ALREADY_ATTACHED,
                "XR_ERROR_ACTIONSETS_ALREADY_ATTACHED"
            },
            {
                XR_ERROR_LOCALIZED_NAME_DUPLICATED,
                "XR_ERROR_LOCALIZED_NAME_DUPLICATED"
            },
            {
                XR_ERROR_LOCALIZED_NAME_INVALID,
                "XR_ERROR_LOCALIZED_NAME_INVALID"
            },
            {
                XR_ERROR_GRAPHICS_REQUIREMENTS_CALL_MISSING,
                "XR_ERROR_GRAPHICS_REQUIREMENTS_CALL_MISSING"
            },
            {
                XR_ERROR_RUNTIME_UNAVAILABLE,
                "XR_ERROR_RUNTIME_UNAVAILABLE"
            },
            {
                XR_ERROR_EXTENSION_DEPENDENCY_NOT_ENABLED,
                "XR_ERROR_EXTENSION_DEPENDENCY_NOT_ENABLED"
            },
            {
                XR_ERROR_PERMISSION_INSUFFICIENT,
                "XR_ERROR_PERMISSION_INSUFFICIENT"
            },
            {
                XR_ERROR_ANDROID_THREAD_SETTINGS_ID_INVALID_KHR,
                "XR_ERROR_ANDROID_THREAD_SETTINGS_ID_INVALID_KHR"
            },
            {
                XR_ERROR_ANDROID_THREAD_SETTINGS_FAILURE_KHR,
                "XR_ERROR_ANDROID_THREAD_SETTINGS_FAILURE_KHR"
            },
            {
                XR_ERROR_CREATE_SPATIAL_ANCHOR_FAILED_MSFT,
                "XR_ERROR_CREATE_SPATIAL_ANCHOR_FAILED_MSFT"
            },
            {
                XR_ERROR_SECONDARY_VIEW_CONFIGURATION_TYPE_NOT_ENABLED_MSFT,
                "XR_ERROR_SECONDARY_VIEW_CONFIGURATION_TYPE_NOT_ENABLED_MSFT"
            },
            {
                XR_ERROR_CONTROLLER_MODEL_KEY_INVALID_MSFT,
                "XR_ERROR_CONTROLLER_MODEL_KEY_INVALID_MSFT"
            },
            {
                XR_ERROR_REPROJECTION_MODE_UNSUPPORTED_MSFT,
                "XR_ERROR_REPROJECTION_MODE_UNSUPPORTED_MSFT"
            },
            {
                XR_ERROR_COMPUTE_NEW_SCENE_NOT_COMPLETED_MSFT,
                "XR_ERROR_COMPUTE_NEW_SCENE_NOT_COMPLETED_MSFT"
            },
            {
                XR_ERROR_SCENE_COMPONENT_ID_INVALID_MSFT,
                "XR_ERROR_SCENE_COMPONENT_ID_INVALID_MSFT"
            },
            {
                XR_ERROR_SCENE_COMPONENT_TYPE_MISMATCH_MSFT,
                "XR_ERROR_SCENE_COMPONENT_TYPE_MISMATCH_MSFT"
            },
            {
                XR_ERROR_SCENE_MESH_BUFFER_ID_INVALID_MSFT,
                "XR_ERROR_SCENE_MESH_BUFFER_ID_INVALID_MSFT"
            },
            {
                XR_ERROR_SCENE_COMPUTE_FEATURE_INCOMPATIBLE_MSFT,
                "XR_ERROR_SCENE_COMPUTE_FEATURE_INCOMPATIBLE_MSFT"
            },
            {
                XR_ERROR_SCENE_COMPUTE_CONSISTENCY_MISMATCH_MSFT,
                "XR_ERROR_SCENE_COMPUTE_CONSISTENCY_MISMATCH_MSFT"
            },
            {
                XR_ERROR_DISPLAY_REFRESH_RATE_UNSUPPORTED_FB,
                "XR_ERROR_DISPLAY_REFRESH_RATE_UNSUPPORTED_FB"
            },
            {
                XR_ERROR_COLOR_SPACE_UNSUPPORTED_FB,
                "XR_ERROR_COLOR_SPACE_UNSUPPORTED_FB"
            },
            {
                XR_ERROR_SPACE_COMPONENT_NOT_SUPPORTED_FB,
                "XR_ERROR_SPACE_COMPONENT_NOT_SUPPORTED_FB"
            },
            {
                XR_ERROR_SPACE_COMPONENT_NOT_ENABLED_FB,
                "XR_ERROR_SPACE_COMPONENT_NOT_ENABLED_FB"
            },
            {
                XR_ERROR_SPACE_COMPONENT_STATUS_PENDING_FB,
                "XR_ERROR_SPACE_COMPONENT_STATUS_PENDING_FB"
            },
            {
                XR_ERROR_SPACE_COMPONENT_STATUS_ALREADY_SET_FB,
                "XR_ERROR_SPACE_COMPONENT_STATUS_ALREADY_SET_FB"
            },
            {
                XR_ERROR_UNEXPECTED_STATE_PASSTHROUGH_FB,
                "XR_ERROR_UNEXPECTED_STATE_PASSTHROUGH_FB"
            },
            {
                XR_ERROR_FEATURE_ALREADY_CREATED_PASSTHROUGH_FB,
                "XR_ERROR_FEATURE_ALREADY_CREATED_PASSTHROUGH_FB"
            },
            {
                XR_ERROR_FEATURE_REQUIRED_PASSTHROUGH_FB,
                "XR_ERROR_FEATURE_REQUIRED_PASSTHROUGH_FB"
            },
            {
                XR_ERROR_NOT_PERMITTED_PASSTHROUGH_FB,
                "XR_ERROR_NOT_PERMITTED_PASSTHROUGH_FB"
            },
            {
                XR_ERROR_INSUFFICIENT_RESOURCES_PASSTHROUGH_FB,
                "XR_ERROR_INSUFFICIENT_RESOURCES_PASSTHROUGH_FB"
            },
            {
                XR_ERROR_UNKNOWN_PASSTHROUGH_FB,
                "XR_ERROR_UNKNOWN_PASSTHROUGH_FB"
            },
            {
                XR_ERROR_RENDER_MODEL_KEY_INVALID_FB,
                "XR_ERROR_RENDER_MODEL_KEY_INVALID_FB"
            },
            {
                XR_RENDER_MODEL_UNAVAILABLE_FB,
                "XR_RENDER_MODEL_UNAVAILABLE_FB"
            },
            {
                XR_ERROR_MARKER_NOT_TRACKED_VARJO,
                "XR_ERROR_MARKER_NOT_TRACKED_VARJO"
            },
            {
                XR_ERROR_MARKER_ID_INVALID_VARJO,
                "XR_ERROR_MARKER_ID_INVALID_VARJO"
            },
            {
                XR_ERROR_MARKER_DETECTOR_PERMISSION_DENIED_ML,
                "XR_ERROR_MARKER_DETECTOR_PERMISSION_DENIED_ML"
            },
            {
                XR_ERROR_MARKER_DETECTOR_LOCATE_FAILED_ML,
                "XR_ERROR_MARKER_DETECTOR_LOCATE_FAILED_ML"
            },
            {
                XR_ERROR_MARKER_DETECTOR_INVALID_DATA_QUERY_ML,
                "XR_ERROR_MARKER_DETECTOR_INVALID_DATA_QUERY_ML"
            },
            {
                XR_ERROR_MARKER_DETECTOR_INVALID_CREATE_INFO_ML,
                "XR_ERROR_MARKER_DETECTOR_INVALID_CREATE_INFO_ML"
            },
            {
                XR_ERROR_MARKER_INVALID_ML,
                "XR_ERROR_MARKER_INVALID_ML"
            },
            {
                XR_ERROR_LOCALIZATION_MAP_INCOMPATIBLE_ML,
                "XR_ERROR_LOCALIZATION_MAP_INCOMPATIBLE_ML"
            },
            {
                XR_ERROR_LOCALIZATION_MAP_UNAVAILABLE_ML,
                "XR_ERROR_LOCALIZATION_MAP_UNAVAILABLE_ML"
            },
            {
                XR_ERROR_LOCALIZATION_MAP_FAIL_ML,
                "XR_ERROR_LOCALIZATION_MAP_FAIL_ML"
            },
            {
                XR_ERROR_LOCALIZATION_MAP_IMPORT_EXPORT_PERMISSION_DENIED_ML,
                "XR_ERROR_LOCALIZATION_MAP_IMPORT_EXPORT_PERMISSION_DENIED_ML"
            },
            {
                XR_ERROR_LOCALIZATION_MAP_PERMISSION_DENIED_ML,
                "XR_ERROR_LOCALIZATION_MAP_PERMISSION_DENIED_ML"
            },
            {
                XR_ERROR_LOCALIZATION_MAP_ALREADY_EXISTS_ML,
                "XR_ERROR_LOCALIZATION_MAP_ALREADY_EXISTS_ML"
            },
            {
                XR_ERROR_LOCALIZATION_MAP_CANNOT_EXPORT_CLOUD_MAP_ML,
                "XR_ERROR_LOCALIZATION_MAP_CANNOT_EXPORT_CLOUD_MAP_ML"
            },
            {
                XR_ERROR_SPATIAL_ANCHORS_PERMISSION_DENIED_ML,
                "XR_ERROR_SPATIAL_ANCHORS_PERMISSION_DENIED_ML"
            },
            {
                XR_ERROR_SPATIAL_ANCHORS_NOT_LOCALIZED_ML,
                "XR_ERROR_SPATIAL_ANCHORS_NOT_LOCALIZED_ML"
            },
            {
                XR_ERROR_SPATIAL_ANCHORS_OUT_OF_MAP_BOUNDS_ML,
                "XR_ERROR_SPATIAL_ANCHORS_OUT_OF_MAP_BOUNDS_ML"
            },
            {
                XR_ERROR_SPATIAL_ANCHORS_SPACE_NOT_LOCATABLE_ML,
                "XR_ERROR_SPATIAL_ANCHORS_SPACE_NOT_LOCATABLE_ML"
            },
            {
                XR_ERROR_SPATIAL_ANCHORS_ANCHOR_NOT_FOUND_ML,
                "XR_ERROR_SPATIAL_ANCHORS_ANCHOR_NOT_FOUND_ML"
            },
            {
                XR_ERROR_SPATIAL_ANCHOR_NAME_NOT_FOUND_MSFT,
                "XR_ERROR_SPATIAL_ANCHOR_NAME_NOT_FOUND_MSFT"
            },
            {
                XR_ERROR_SPATIAL_ANCHOR_NAME_INVALID_MSFT,
                "XR_ERROR_SPATIAL_ANCHOR_NAME_INVALID_MSFT"
            },
            {
                XR_SCENE_MARKER_DATA_NOT_STRING_MSFT,
                "XR_SCENE_MARKER_DATA_NOT_STRING_MSFT"
            },
            {
                XR_ERROR_SPACE_MAPPING_INSUFFICIENT_FB,
                "XR_ERROR_SPACE_MAPPING_INSUFFICIENT_FB"
            },
            {
                XR_ERROR_SPACE_LOCALIZATION_FAILED_FB,
                "XR_ERROR_SPACE_LOCALIZATION_FAILED_FB"
            },
            {
                XR_ERROR_SPACE_NETWORK_TIMEOUT_FB,
                "XR_ERROR_SPACE_NETWORK_TIMEOUT_FB"
            },
            {
                XR_ERROR_SPACE_NETWORK_REQUEST_FAILED_FB,
                "XR_ERROR_SPACE_NETWORK_REQUEST_FAILED_FB"
            },
            {
                XR_ERROR_SPACE_CLOUD_STORAGE_DISABLED_FB,
                "XR_ERROR_SPACE_CLOUD_STORAGE_DISABLED_FB"
            },
            {
                XR_ERROR_SPACE_INSUFFICIENT_RESOURCES_META,
                "XR_ERROR_SPACE_INSUFFICIENT_RESOURCES_META"
            },
            {
                XR_ERROR_SPACE_STORAGE_AT_CAPACITY_META,
                "XR_ERROR_SPACE_STORAGE_AT_CAPACITY_META"
            },
            {
                XR_ERROR_SPACE_INSUFFICIENT_VIEW_META,
                "XR_ERROR_SPACE_INSUFFICIENT_VIEW_META"
            },
            {
                XR_ERROR_SPACE_PERMISSION_INSUFFICIENT_META,
                "XR_ERROR_SPACE_PERMISSION_INSUFFICIENT_META"
            },
            {
                XR_ERROR_SPACE_RATE_LIMITED_META,
                "XR_ERROR_SPACE_RATE_LIMITED_META"
            },
            {
                XR_ERROR_SPACE_TOO_DARK_META,
                "XR_ERROR_SPACE_TOO_DARK_META"
            },
            {
                XR_ERROR_SPACE_TOO_BRIGHT_META,
                "XR_ERROR_SPACE_TOO_BRIGHT_META"
            },
            {
                XR_ERROR_PASSTHROUGH_COLOR_LUT_BUFFER_SIZE_MISMATCH_META,
                "XR_ERROR_PASSTHROUGH_COLOR_LUT_BUFFER_SIZE_MISMATCH_META"
            },
            {
                XR_ENVIRONMENT_DEPTH_NOT_AVAILABLE_META,
                "XR_ENVIRONMENT_DEPTH_NOT_AVAILABLE_META"
            },
            {
                XR_ERROR_RENDER_MODEL_ID_INVALID_EXT,
                "XR_ERROR_RENDER_MODEL_ID_INVALID_EXT"
            },
            {
                XR_ERROR_RENDER_MODEL_ASSET_UNAVAILABLE_EXT,
                "XR_ERROR_RENDER_MODEL_ASSET_UNAVAILABLE_EXT"
            },
            {
                XR_ERROR_RENDER_MODEL_GLTF_EXTENSION_REQUIRED_EXT,
                "XR_ERROR_RENDER_MODEL_GLTF_EXTENSION_REQUIRED_EXT"
            },
            {
                XR_ERROR_NOT_INTERACTION_RENDER_MODEL_EXT,
                "XR_ERROR_NOT_INTERACTION_RENDER_MODEL_EXT"
            },
            {
                XR_ERROR_HINT_ALREADY_SET_QCOM,
                "XR_ERROR_HINT_ALREADY_SET_QCOM"
            },
            {
                XR_ERROR_NOT_AN_ANCHOR_HTC,
                "XR_ERROR_NOT_AN_ANCHOR_HTC"
            },
            {
                XR_ERROR_SPATIAL_ENTITY_ID_INVALID_BD,
                "XR_ERROR_SPATIAL_ENTITY_ID_INVALID_BD"
            },
            {
                XR_ERROR_SPATIAL_SENSING_SERVICE_UNAVAILABLE_BD,
                "XR_ERROR_SPATIAL_SENSING_SERVICE_UNAVAILABLE_BD"
            },
            {
                XR_ERROR_ANCHOR_NOT_SUPPORTED_FOR_ENTITY_BD,
                "XR_ERROR_ANCHOR_NOT_SUPPORTED_FOR_ENTITY_BD"
            },
            {
                XR_ERROR_SPATIAL_ANCHOR_NOT_FOUND_BD,
                "XR_ERROR_SPATIAL_ANCHOR_NOT_FOUND_BD"
            },
            {
                XR_ERROR_SPATIAL_ANCHOR_SHARING_NETWORK_TIMEOUT_BD,
                "XR_ERROR_SPATIAL_ANCHOR_SHARING_NETWORK_TIMEOUT_BD"
            },
            {
                XR_ERROR_SPATIAL_ANCHOR_SHARING_AUTHENTICATION_FAILURE_BD,
                "XR_ERROR_SPATIAL_ANCHOR_SHARING_AUTHENTICATION_FAILURE_BD"
            },
            {
                XR_ERROR_SPATIAL_ANCHOR_SHARING_NETWORK_FAILURE_BD,
                "XR_ERROR_SPATIAL_ANCHOR_SHARING_NETWORK_FAILURE_BD"
            },
            {
                XR_ERROR_SPATIAL_ANCHOR_SHARING_LOCALIZATION_FAIL_BD,
                "XR_ERROR_SPATIAL_ANCHOR_SHARING_LOCALIZATION_FAIL_BD"
            },
            {
                XR_ERROR_SPATIAL_ANCHOR_SHARING_MAP_INSUFFICIENT_BD,
                "XR_ERROR_SPATIAL_ANCHOR_SHARING_MAP_INSUFFICIENT_BD"
            },
            {
                XR_ERROR_SCENE_CAPTURE_FAILURE_BD,
                "XR_ERROR_SCENE_CAPTURE_FAILURE_BD"
            },
            {
                XR_ERROR_SPACE_NOT_LOCATABLE_EXT,
                "XR_ERROR_SPACE_NOT_LOCATABLE_EXT"
            },
            {
                XR_ERROR_PLANE_DETECTION_PERMISSION_DENIED_EXT,
                "XR_ERROR_PLANE_DETECTION_PERMISSION_DENIED_EXT"
            },
            {
                XR_ERROR_MISMATCHING_TRACKABLE_TYPE_ANDROID,
                "XR_ERROR_MISMATCHING_TRACKABLE_TYPE_ANDROID"
            },
            {
                XR_ERROR_TRACKABLE_TYPE_NOT_SUPPORTED_ANDROID,
                "XR_ERROR_TRACKABLE_TYPE_NOT_SUPPORTED_ANDROID"
            },
            {
                XR_ERROR_ANCHOR_ID_NOT_FOUND_ANDROID,
                "XR_ERROR_ANCHOR_ID_NOT_FOUND_ANDROID"
            },
            {
                XR_ERROR_ANCHOR_ALREADY_PERSISTED_ANDROID,
                "XR_ERROR_ANCHOR_ALREADY_PERSISTED_ANDROID"
            },
            {
                XR_ERROR_ANCHOR_NOT_TRACKING_ANDROID,
                "XR_ERROR_ANCHOR_NOT_TRACKING_ANDROID"
            },
            {
                XR_ERROR_PERSISTED_DATA_NOT_READY_ANDROID,
                "XR_ERROR_PERSISTED_DATA_NOT_READY_ANDROID"
            },
            {
                XR_ERROR_SERVICE_NOT_READY_ANDROID,
                "XR_ERROR_SERVICE_NOT_READY_ANDROID"
            },
            {
                XR_ERROR_FUTURE_PENDING_EXT,
                "XR_ERROR_FUTURE_PENDING_EXT"
            },
            {
                XR_ERROR_FUTURE_INVALID_EXT,
                "XR_ERROR_FUTURE_INVALID_EXT"
            },
            {
                XR_ERROR_SYSTEM_NOTIFICATION_PERMISSION_DENIED_ML,
                "XR_ERROR_SYSTEM_NOTIFICATION_PERMISSION_DENIED_ML"
            },
            {
                XR_ERROR_SYSTEM_NOTIFICATION_INCOMPATIBLE_SKU_ML,
                "XR_ERROR_SYSTEM_NOTIFICATION_INCOMPATIBLE_SKU_ML"
            },
            {
                XR_ERROR_WORLD_MESH_DETECTOR_PERMISSION_DENIED_ML,
                "XR_ERROR_WORLD_MESH_DETECTOR_PERMISSION_DENIED_ML"
            },
            {
                XR_ERROR_WORLD_MESH_DETECTOR_SPACE_NOT_LOCATABLE_ML,
                "XR_ERROR_WORLD_MESH_DETECTOR_SPACE_NOT_LOCATABLE_ML"
            },
            {
                XR_ERROR_FACIAL_EXPRESSION_PERMISSION_DENIED_ML,
                "XR_ERROR_FACIAL_EXPRESSION_PERMISSION_DENIED_ML"
            },
            {
                XR_ERROR_COLOCATION_DISCOVERY_NETWORK_FAILED_META,
                "XR_ERROR_COLOCATION_DISCOVERY_NETWORK_FAILED_META"
            },
            {
                XR_ERROR_COLOCATION_DISCOVERY_NO_DISCOVERY_METHOD_META,
                "XR_ERROR_COLOCATION_DISCOVERY_NO_DISCOVERY_METHOD_META"
            },
            {
                XR_COLOCATION_DISCOVERY_ALREADY_ADVERTISING_META,
                "XR_COLOCATION_DISCOVERY_ALREADY_ADVERTISING_META"
            },
            {
                XR_COLOCATION_DISCOVERY_ALREADY_DISCOVERING_META,
                "XR_COLOCATION_DISCOVERY_ALREADY_DISCOVERING_META"
            },
            {
                XR_ERROR_SPACE_GROUP_NOT_FOUND_META,
                "XR_ERROR_SPACE_GROUP_NOT_FOUND_META"
            },
            {
                XR_ERROR_ANCHOR_NOT_OWNED_BY_CALLER_ANDROID,
                "XR_ERROR_ANCHOR_NOT_OWNED_BY_CALLER_ANDROID"
            },
            {
                XR_ERROR_IMAGE_FORMAT_UNSUPPORTED_ANDROID,
                "XR_ERROR_IMAGE_FORMAT_UNSUPPORTED_ANDROID"
            },
            {
                XR_ERROR_SPATIAL_CAPABILITY_UNSUPPORTED_EXT,
                "XR_ERROR_SPATIAL_CAPABILITY_UNSUPPORTED_EXT"
            },
            {
                XR_ERROR_SPATIAL_ENTITY_ID_INVALID_EXT,
                "XR_ERROR_SPATIAL_ENTITY_ID_INVALID_EXT"
            },
            {
                XR_ERROR_SPATIAL_BUFFER_ID_INVALID_EXT,
                "XR_ERROR_SPATIAL_BUFFER_ID_INVALID_EXT"
            },
            {
                XR_ERROR_SPATIAL_COMPONENT_UNSUPPORTED_FOR_CAPABILITY_EXT,
                "XR_ERROR_SPATIAL_COMPONENT_UNSUPPORTED_FOR_CAPABILITY_EXT"
            },
            {
                XR_ERROR_SPATIAL_CAPABILITY_CONFIGURATION_INVALID_EXT,
                "XR_ERROR_SPATIAL_CAPABILITY_CONFIGURATION_INVALID_EXT"
            },
            {
                XR_ERROR_SPATIAL_COMPONENT_NOT_ENABLED_EXT,
                "XR_ERROR_SPATIAL_COMPONENT_NOT_ENABLED_EXT"
            },
            {
                XR_ERROR_SPATIAL_PERSISTENCE_SCOPE_UNSUPPORTED_EXT,
                "XR_ERROR_SPATIAL_PERSISTENCE_SCOPE_UNSUPPORTED_EXT"
            },
            {
                XR_ERROR_SPATIAL_PERSISTENCE_SCOPE_INCOMPATIBLE_EXT,
                "XR_ERROR_SPATIAL_PERSISTENCE_SCOPE_INCOMPATIBLE_EXT"
            },
            {
                XR_ERROR_EXTENSION_DEPENDENCY_NOT_ENABLED_KHR,
                "XR_ERROR_EXTENSION_DEPENDENCY_NOT_ENABLED_KHR"
            },
            {
                XR_ERROR_PERMISSION_INSUFFICIENT_KHR,
                "XR_ERROR_PERMISSION_INSUFFICIENT_KHR"
            },
        };

        return std::formatter<std::string>::format(map.at(result), context);
    }
};

template<>
struct std::formatter<XrSessionState> : std::formatter<std::string>
{
    template<typename Context>
    auto format(const XrSessionState &result, Context &context) const
    {
        static const std::map<XrSessionState, const char *> map
        {
            { XR_SESSION_STATE_UNKNOWN, "XR_SESSION_STATE_UNKNOWN" },
            { XR_SESSION_STATE_IDLE, "XR_SESSION_STATE_IDLE" },
            { XR_SESSION_STATE_READY, "XR_SESSION_STATE_READY" },
            { XR_SESSION_STATE_SYNCHRONIZED, "XR_SESSION_STATE_SYNCHRONIZED" },
            { XR_SESSION_STATE_VISIBLE, "XR_SESSION_STATE_VISIBLE" },
            { XR_SESSION_STATE_FOCUSED, "XR_SESSION_STATE_FOCUSED" },
            { XR_SESSION_STATE_STOPPING, "XR_SESSION_STATE_STOPPING" },
            { XR_SESSION_STATE_LOSS_PENDING, "XR_SESSION_STATE_LOSS_PENDING" },
            { XR_SESSION_STATE_EXITING, "XR_SESSION_STATE_EXITING" },
        };

        return std::formatter<std::string>::format(map.at(result), context);
    }
};

template<>
struct std::formatter<XrReferenceSpaceType> : std::formatter<std::string>
{
    template<typename Context>
    auto format(const XrReferenceSpaceType &result, Context &context) const
    {
        static const std::map<XrReferenceSpaceType, const char *> map
        {
            { XR_REFERENCE_SPACE_TYPE_VIEW, "XR_REFERENCE_SPACE_TYPE_VIEW" },
            { XR_REFERENCE_SPACE_TYPE_LOCAL, "XR_REFERENCE_SPACE_TYPE_LOCAL" },
            { XR_REFERENCE_SPACE_TYPE_STAGE, "XR_REFERENCE_SPACE_TYPE_STAGE" },
            { XR_REFERENCE_SPACE_TYPE_LOCAL_FLOOR, "XR_REFERENCE_SPACE_TYPE_LOCAL_FLOOR" },
            { XR_REFERENCE_SPACE_TYPE_UNBOUNDED_MSFT, "XR_REFERENCE_SPACE_TYPE_UNBOUNDED_MSFT" },
            { XR_REFERENCE_SPACE_TYPE_COMBINED_EYE_VARJO, "XR_REFERENCE_SPACE_TYPE_COMBINED_EYE_VARJO" },
            { XR_REFERENCE_SPACE_TYPE_LOCALIZATION_MAP_ML, "XR_REFERENCE_SPACE_TYPE_LOCALIZATION_MAP_ML" },
            { XR_REFERENCE_SPACE_TYPE_LOCAL_FLOOR_EXT, "XR_REFERENCE_SPACE_TYPE_LOCAL_FLOOR_EXT" },
        };

        return std::formatter<std::string>::format(map.at(result), context);
    }
};
